---
title: "exercises for section 5.2.4"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
tutorial_options(exercise.checker = gradethis::grade_learnr)
knitr::opts_chunk$set(echo = FALSE)
library(nycflights13)
library(tidyverse)
```


## Easy

### question 1

Write the code to find the flights that had an arrival delay of 60 minutes or more.

```{r two-plus-two, exercise=TRUE}

```
```{r two-plus-two-hint-1}
"filter(flights, arr_delay >="
```

```{r two-plus-two-solution}
filter(flights, arr_delay >= 60)
```
```{r two-plus-two-check}
gradethis::grade_code()
```


## Moderate 

### question 2

wirte the code to find flights that departed between January and August

```{r two-plus-three, exercise=TRUE}

```
```{r two-plus-three-hint-1}
filter(flights, month >= , month <= )
```
```{r two-plus-three-solution}
filter(flights, month >= 7, month <= 9)
```
```{r two-plus-three-check}
gradethis::grade_code()
```


## Hard

### question 

find the flights that Departed between midnight and 6am (inclusive).

```{r two-plus-four, exercise=TRUE}

```
```{r two-plus-four-solution}
summary(flights$dep_time)
filter(flights, dep_time <= 600 | dep_time == 2400)
c(600, 1200, 2400) %% 2400
filter(flights, dep_time %% 2400 <= 600)
```

```{r two-plus-four-check}
gradethis::grade_code()
```


