---
title: "exercises for section 5.4.1"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
tutorial_options(exercise.checker = gradethis::grade_learnr)
knitr::opts_chunk$set(echo = FALSE)
library(nycflights13)
library(tidyverse)
```


## Easy

### question 1

Use any_of () function to find dep_delay and dep_time vectors. 

```{r two-plus-two, exercise=TRUE}

```

```{r two-plus-two-hint-1}
"select(flights, any_of(c()))"
```

```{r two-plus-two-solution}
select(flights, any_of(c("dep_time", "dep_delay", "arr_time", "arr_delay")))
```

```{r two-plus-two-check}
gradethis::grade_code()
```




## modrate

### question 2

find the vectors dep_time, dep_delay, arr_time, arr_delay without using dep_time, dep_delay, arr_time, arr_delay in the function,, use the starts_with()function.

```{r two-plus-three, exercise=TRUE}

```
```{r two-plus-three-solution}
select(flights, starts_with("dep_"), starts_with("arr_"))
```
```{r two-plus-three-check}
gradethis::grade_code()
```
## Hard

### question 3

use the !! operator in a function to find the vectors of "dep_time", "dep_delay", "arr_time", "arr_delay".

```{r two-plus-four, exercise=TRUE}

```
```{r two-plus-four-hint-1}
 "Specify the names of the variables with a character vector and use the bang-bang operator (use c as a name for the variables) (!!)."
```
```{r two-plus-four-solution}
variables <- c("dep_time", "dep_delay", "arr_time", "arr_delay")
select(flights, !!variables)
```
```{r two-plus-four-check}
gradethis::grade_code()
```




