---
title: "exercises for section 5.5.2"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
tutorial_options(exercise.checker = gradethis::grade_learnr)
knitr::opts_chunk$set(echo = FALSE)
library(nycflights13)
library(tidyverse)
```


## Easy

### question 1

```{r quiz}
question("what would the following code 1504 %/% 100 give",
  answer("[1] 15", correct = TRUE),
  answer("[1] 4"),
  answer("150,400"),
  answer("15.04")
)
```

## Moderate

### question 2

```{r quiz1}
question(" what does the following give us 1:3 + 1:10",
  answer("[1]  2  4  6  5  7  9  8 10 12 11", correct = TRUE),
  answer("[1]  2  4  6  5  7  9  9 10 12 11"),
  answer("[1]  2  3  4  5  6  7  8 9 10 11"),
  answer("gives us nothing")
)
```

## Hard

### question 3

Find the 10 most delayed flights using a ranking function.

```{r two-plus-four, exercise=TRUE}

```

```{r two-plus-four-solution}
rankme <- tibble(
  x = c(10, 5, 1, 5, 5)
)
rankme <- mutate(rankme,
  x_row_number = row_number(x),
  x_min_rank = min_rank(x),
  x_dense_rank = dense_rank(x)
)
arrange(rankme, x)
flights_delayed <- mutate(flights, 
                          dep_delay_min_rank = min_rank(desc(dep_delay)),
                          dep_delay_row_number = row_number(desc(dep_delay)),
                          dep_delay_dense_rank = dense_rank(desc(dep_delay))
                          )
flights_delayed <- filter(flights_delayed, 
                          !(dep_delay_min_rank > 10 | dep_delay_row_number > 10 |
                              dep_delay_dense_rank > 10))
flights_delayed <- arrange(flights_delayed, dep_delay_min_rank)
print(select(flights_delayed, month, day, carrier, flight, dep_delay, 
             dep_delay_min_rank, dep_delay_row_number, dep_delay_dense_rank), 
      n = Inf)
```

```{r two-plus-four-check}
gradethis::grade_code()
```
